#!/usr/bin/env bash
# Bash script that displays that displays the content of the file /etc/passwd.

while read -r line; do
	token=$(echo "$line" | cut -d':' -f1,3,6 )
	echo "$token"
done < /etc/passwd
