#!/usr/bin/env bash
# This script prints the time for 12 hours and 59 minutesthe time for 12 hours and 59 minutes.

Hour="0"
Min="1"

while [ $Hour -le 12 ]
do
	echo "Hour: $Hour"
	while [ $Min -lt 60 ]
	do
		echo "$Min"
		(( Min += 1))
	done
	Min="1"
	(( Hour += 1 ))
done
